version: "3.8"

services:
  # Frontend GESCOMPH - STAGING
  gescomph-front-staging:
    container_name: ${CONTAINER_NAME}
    build:
      context: ../..
      dockerfile: Dockerfile
    image: ${IMAGE_NAME}:latest
    ports:
      - "4203:${PORT}"
    restart: always
    env_file:
      - .env
    networks:
      - network_staging
    labels:
      - com.gescomph.environment=staging

networks:
  network_staging:
    driver: bridge
